version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=e_shoper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ksy12345

  web:
    #build: . #command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application
    image: tipu247/ecommerce:latest
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount custom nginx.conf
      - static_volume:/app/static # Volume for static files
    depends_on:
      - web
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8051:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  static_volume:
