apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devxhub
data:
  nginx.conf: |
    worker_processes 1;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
    
        sendfile on;
        keepalive_timeout 65;
    
        server {
            listen 80;
            server_name localhost;
    
            # Serve static files
            location /static/ {
                alias /app/static/static_root/;  # Nginx serves static files from here
            }
    
            # Proxy dynamic requests to Django
            location / {
                proxy_pass http://django-service:8000;  # Forward to Django service
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }

