apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: devxhub
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/postgres
    server: 172.16.188.131  # NFS server IP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devxhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

